# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- 'self-agent'

pool:
  name: 'MyAgentPool'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: 'npm install'
  displayName: 'Run npm install'

- script: 'npm run scan-code-ci'
  displayName: 'Run npm run scan-code-ci'

- script: 'npm run ci-test'
  displayName: 'Run npm run ci-test'

- script: 'npm run ci-build'
  displayName: 'Run npm run ci-build'

- script: 'npm run netlify-deploy'
  displayName: 'Run npm run netlify-deploy'


