# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: 'npm install'
  displayName: 'Run npm install'

- script: 'npm run ci-test'
  displayName: 'Run npm run unit-test'

- script: 'npm run ci-build'
  displayName: 'Run npm run build'
